- hosts: switches
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks: 
    - name: Merge vlan with current device configuration
      ios_vlan:
        config:
          - { vlan_id: 10, name: test-vlan10, interfaces: GigabitEthernet0/3 }
          - { vlan_id: 20, name: test-vlan20, interfaces: GigabitEthernet0/4 }
      register: reg_merge_vlan
      timeout: 10
      ignore_errors: yes  
