- hosts: sw-core
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks: 
    - name: Get arp results
      ansible.utils.cli_parse:
        command: show ip arp
        parser:
          name: ansible.utils.textfsm
          template_path: cisco_ios_show_ip_arp.textfsm
        set_fact: show_ip_arp
  

    - name: Display parsed ARP table
      debug:
        var: arpParsed.stdout_lines  
