- hosts: sw-core
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks: 
    - name: Get arp results
      ansible.utils.cli_parse:
        command: show arp
        parser:
          name: ansible.utils.textfsm
          template_path: cisco_ios_show_ip_arp.textfsm
        set_fact: show_ip_arp 

    #- name: Display parsed ARP table
    #  debug:
    #    var: show_ip_arp

    - name: Get macTable results
      ansible.utils.cli_parse:
        command: show mac address-table
        parser:
          name: ansible.utils.textfsm
          template_path: cisco_ios_show_mac-address-table.textfsm
        set_fact: show_mac_table 

    #- name: Display parsed MAC table
    #  debug:
    #    var: show_mac_table

    - name: Find results based on searchIp variable
      set_fact:
        results: |-
          {% set result = []                                                                -%}
          {% for arpRow in show_ip_arp                                                      -%}
          {%      mdebug(arpRow.IP_ADDRESS) -%}
          {%   if arpRow.IP_ADDRESS[0] == searchIp                                             -%}
          {%    for macRow in show_mac_table                                                -%}
          {%      if macRow.DESTINATION_ADDRESS[0] == arpRow.MAC_ADDRESS[0]                       -%}
          {%        set interface = macRow.DESTINATION_PORT[0]                              -%}
          {%        set dummy = result.append(inventory_hostname + " -> " + interface )     -%}
          {%      endif                                                                     -%}
          {%    endfor                                                                      -%}
          {%   endif                                                                        -%}
          {% endfor                                                                         -%}
          {{ result }} 
    
    - name: Display results
      debug:
        var: results
