- hosts: sw-core
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks: 
    - name: Get arp results
      cisco.ios.ios_command:
        commands: show arp
      register: arp_output

    - name: Parse ARP table using Jinja2
      set_fact:
        arpParsed: |-
          {% for line in arp_output.stdout_lines %}
              {% if line | regex_match('^(Internet|Protocol)') %}
                 
              {% else %}
              
                {% set arp_entry = line | regex_replace('\\s+', ' ') | regex_replace('^\\s|\\s$', '') | split(' ') %}
                
                {% if arp_entry | length == 3 %}
                {%    IP: arp_entry[0] , MAC: arp_entry[1], Interface: arp_entry[2] %}
                {% endif %}

              {% endif %}

          {% endfor %}

    - name: Display parsed ARP table
      debug:
        var: arpParsed.stdout_lines  
