- hosts: switches
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks:
    ##############################################################################################
    - name: IOS SHOW VERSION (first)
    ##############################################################################################
      cisco.ios.ios_command:
        commands: 
          - show run
        retries: 1
      register: reg_show_ver
      timeout: 10
      ignore_errors: yes
      
    - name: F*cking Meta
      meta: end_host
      when: reg_show_ver is not defined or reg_show_ver.failed

    ##############################################################################################
    #- name: COMPOSE RESULT
    ##############################################################################################
    #  become: no
    #  set_fact: 
    #    connection: none
    #    _result: "{{ reg_show_ver.stdout[0] | join('\n') }}" 
 
    - name: PrintOut
      debug:
        msg:
          #- "{% for item in reg_show_ver.stdout_lines[0] %}{{ item + '\n'}}{% endfor %}"
          - {{ reg_show_ver.stdout_lines }}

    # BLOCK
    #ignore_errors: true
  #BLOCK
