- hosts: switches
  strategy: linear
  serial: 1000   
  gather_facts: no
  ignore_unreachable: true
  tasks:  
    - block: 
      - name: IOS SHOW VERSION  
        cisco.ios.ios_command:
          commands: 
            - show run
          retries: 1
        register: reg_show_ver
        timeout: 10
        ignore_errors: yes

      ##############################################################################################
      #- name: COMPOSE RESULT
      ##############################################################################################
      #  become: no
      #  set_fact: 
      #    connection: none
      #    _result: "{{ reg_show_ver.stdout[0] | join('\n') }}" 
  
      - name: PrintOut
        debug:
          msg:
            #- "{% for item in reg_show_ver.stdout_lines[0] %}{{ item + '\n'}}{% endfor %}"
            - "{{ reg_show_ver.stdout_lines[0] }}"
 
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios 
        ansible_user: '{{ rhsm_username }}'
        ansible_ssh_pass: '{{ rhsm_password }}'
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: '{{ rhsm_password }}'

    - block:
      #ottengo la data
      - setup:
          gather_subset:
            - 'min'
      - set_fact:
          fileName: "{{inventory_hostname + ' - ' + lookup('pipe','date +%Y%m%d%H%M%S')}}"
      - name: CreateReport
        ansible.builtin.template: 
          src: printshrun.j2
          dest: "/var/ansibleOutput/report-{{fileName}}.html"
        delegate_to: scpServer
        register: template_output
        

    # BLOCK
    #ignore_errors: true
  #BLOCK
