- hosts: switches
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks:
    ##############################################################################################
    - name: IOS SHOW VERSION (first)
    ##############################################################################################
      cisco.ios.ios_command:
        commands: 
          - show run
        retries: 1
      register: reg_show_ver
      timeout: 10
      ignore_errors: yes

    ##############################################################################################
    #- name: COMPOSE RESULT
    ##############################################################################################
    #  become: no
    #  set_fact: 
    #    connection: none
    #    _result: "{{ reg_show_ver.stdout[0] | join('\n') }}" 
 
    - name: PrintOut
      debug:
        msg:
          #- "{% for item in reg_show_ver.stdout_lines[0] %}{{ item + '\n'}}{% endfor %}"
          - "{{ reg_show_ver.stdout_lines[0] }}"

    - name: CreateReport
      ansible.builtin.template: 
        src: template.j2
        dest: "/tmp/report.html" 
      delegate_to: scpServer
      register: template_output

    - name: Get the list of files in /tmp folder 
      ansible.builtin.shell: 
        cmd: ls -l 
        chdir: "/tmp" 
      register: scpsvr_ls_out

    - name: Print /tmp folder files 
      debug: 
        var: scpsvr_ls_out.stdout_lines

    - name: Print scpServer host details 
      debug: 
        msg: 
          "Hostname FQDN: {{ hostvars[inventory_hostname]['ansible_fqdn'] }} "
          "Hostname : {{ hostvars[inventory_hostname]['ansible_hostname'] }} "
          "All IP Addresses: {{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] }} "
          "Default IPv4 Address: {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} "
          "Mounts: {{ hostvars[inventory_hostname]['ansible_mounts'] | map(attribute='mount') }} "

    - name: Print scpServer Facts 
      debug: 
        var: hostvars[inventory_hostname]
      delegate_to: scpServer
      
    # BLOCK
    #ignore_errors: true
  #BLOCK
