- hosts: scpServer
  gather_facts: no
  strategy: linear
  serial: 1000 
  
  tasks: 
    - name: Get the list of files in /tmp folder 
      ansible.builtin.shell: 
        cmd: ifconfig
        chdir: "/"  
      delegate_to: scpServer
      register: scpsvr_ls_out

    - name: Print /tmp folder files 
      debug: 
        var: scpsvr_ls_out.stdout_lines
