---
- hosts: switches
  become: yes
  gather_facts: no 

  vars: # for execution environment
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become_method: enable
    ansible_become_password: "cisco123"
    
  tasks:
    - name: Run show version on remote devices
      cisco.ios.ios_command:
          commands: show version
