- hosts: switches
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks:
    ##############################################################################################
    - name: IOS SHOW VERSION (first)
    ##############################################################################################
      ansible.builtin.copy:
        src: /tmp/test.txt
        dest: /tmp/foo.conf 
      delegate_to: scpServer
 
   
