- hosts: switches
  gather_facts: no
  strategy: linear
  serial: 1000 

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: 'asd'
    ansible_ssh_pass: 'fff'
    ansible_become: yes
    ansible_become_method: enable
    reg_show_ver: 'fff'

  tasks:        
    - name: CreateReport
      ansible.builtin.template: 
        src: template.j2
        dest: "/home/coeadmin/Desktop/report.html" 
      delegate_to: scpServer

    - name: Use stat module to find the file details 
      ansible.builtin.stat: 
        path: /home/coeadmin/Desktop/report.html
      register: reg_stat_out 
      delegate_to: scpServer
    
    - name: Print file details 
      debug: msg: "{{ reg_stat_out }}"

    ##############################################################################################
    - name: IOS SHOW VERSION (first)
    ##############################################################################################
      ansible.builtin.copy:
        src: /home/coeadmin/Desktop/test.txt
        dest: /home/coeadmin/Desktop/foo.conf 
        remote_src: yes
      delegate_to: scpServer
      
 
   
