- hosts: switches
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: 'asd'
    ansible_ssh_pass: 'fff'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 'fff'

  tasks:
    - name: Create Variable 
      reg_show_ver: test123

    - name: CreateReport
      ansible.builtin.template: 
        src: template.j2
        dest: "/tmp/report.html" 
      delegate_to: scpServer
    
    ##############################################################################################
    - name: IOS SHOW VERSION (first)
    ##############################################################################################
      ansible.builtin.copy:
        src: /tmp/test.txt
        dest: /tmp/foo.conf 
        remote_src: yes
      delegate_to: scpServer
      
 
   
