- hosts: switches
  gather_facts: no
  strategy: linear
  serial: 1000
  user: root
  sudo: yes

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: 'asd'
    ansible_ssh_pass: 'fff'
    ansible_become: yes
    ansible_become_method: enable
    reg_show_ver: 'fff'

  tasks:  
    - name: touch
      file: path=/home/coeadmin/Desktop/test1.txt state=touch
      delegate_to: scpServer
      
    - name: file
      file: path=/home/coeadmin/Desktop/test1.txt mode=777
      delegate_to: scpServer
      
    - name: CreateReport
      ansible.builtin.template: 
        src: template.j2
        dest: "/home/coeadmin/Desktop/report.html" 
      delegate_to: scpServer
    
    ##############################################################################################
    - name: IOS SHOW VERSION (first)
    ##############################################################################################
      ansible.builtin.copy:
        src: /home/coeadmin/Desktop/test.txt
        dest: /home/coeadmin/Desktop/foo.conf 
        remote_src: yes
      delegate_to: scpServer
      
 
   
