- hosts: '{{ selectedHost }}'
  gather_facts: no
  strategy: linear
  serial: 1000

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios 
    ansible_user: '{{ rhsm_username }}'
    ansible_ssh_pass: '{{ rhsm_password }}'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '{{ rhsm_password }}'

  tasks:
    - name: Shut interface
      block:
        - name: Merge new vlan with current device configuration
          cisco.ios.ios_command:
            commands:
              - conf t
              - int {{ shutInterface }}
              - shut
          
        - name: Merge new vlan with current device configuration
          cisco.ios.ios_command:
            commands:
              - conf t
              - int {{ noshutInterface }}
              - noshut

      when: model|lower is search("c9300-24ub")
      ignore_errors: true
