---
- name: Listen for events on a webhook
  hosts: all
 
  ## Define our source for events
 
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
 
  ## Define the conditions we are looking for
 
  rules:
    - name: "Test payload"
      condition: event.payload is defined
      action:
        debug:
